OnlineStore.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Models;
using OnlineStore.Services;

namespace OnlineStore.Web.Controllers
{


    //注入购物车服务
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }
        public IActionResult Index()
        {
            var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Id").Value);
            IEnumerable<ProductInCart> products = _cartService.GetProductInCart(userId);
            return View(products);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int productId, int quantity)
        {
            await _cartService.UpdateQuantityAsync(productId, quantity);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int productId)
        {
            await _cartService.RemoveProduct(productId);
            return RedirectToAction(nameof(Index));
        }

    }
}

OnlineStore.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Models;
using OnlineStore.Services;
using OnlineStore.Web.Models.Orders;
using OnlineStore.Web.Models.ProductDetails;
using OnlineStore.Web.Models.User;

namespace OnlineStore.Web.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {

        private readonly IOrderService _orderService;
        private readonly IAccountService _accountService;
        private readonly ICartService _cartService;
        private readonly IProductService _productService;



        public OrdersController(IOrderService orderService, 
            ICartService cartService,
            IProductService productService,
            IAccountService accountService)
        {
            _orderService = orderService;
            _cartService = cartService;
            _productService = productService;
            _accountService = accountService;
        }


        /// <summary>
        /// 展示当前用户的下单后的订单
        /// 加载订单数据，但是不加载订单详情
        /// </summary>
        /// <returns></returns>
        /// 
        public IActionResult Index()
        {
            IndexOrderViewModel indexOrderViewModel = new IndexOrderViewModel
            {
                wait = _orderService.FindOrderWithState(OrderState.WaitToDeal),
                Shipped = _orderService.FindOrderWithState(OrderState.Shipped),
                completed = _orderService.FindOrderWithState(OrderState.Completed)
            };
            return View(indexOrderViewModel);
        }




        [HttpPost]
        /// <summary>
        /// 展示当前用户的所有订单内容
        /// 加载订单数据，但是不加载订单详情
        /// </summary>
        /// <returns></returns>
        public IActionResult ShowAllInfo()
        {
            var OderVm = new ShowOrdersViewModel
            {
                AllOrdersInfo = _orderService.FindAllOrders()
            };
            return View(OderVm);
        }




        /// <summary>
        /// 用户选择编辑订单
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit()
        {
            var editVm = new Models.Contact.EditViewModel();
            return View(editVm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Models.Contact.EditViewModel model)
        {
            return RedirectToAction(nameof(Index));
        }


        /// <summary>
        /// 用户选择删除订单(退订单)
        /// </summary>
        /// <returns></returns>
        //public IActionResult Delete()
        //{
        //    var deleteVm = new DeleteViewModel();
        //    return View(deleteVm);
        //}

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteViewModel model)
        {
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// 提交评论到数据库
        /// </summary>
        /// <returns></returns>
        ///        [Authorize]
        public IActionResult SendComment(int ProductId)
        {
            CommentModelView commentModelView = new CommentModelView
            {
                productId = ProductId
            };
            return View(commentModelView);
        }

        [HttpPost]
        public async Task<IActionResult> SendComment(CommentModelView model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);//未添加model
            }
            var SComment = new ProductComment
            {
                Id =model.productId,
                Description = model.commentString,
                Score = model.Score
            };
            await _productService.AddComment(model.productId,Convert.ToInt32( User.Claims.FirstOrDefault(u=>u.Type=="Id").Value), SComment);


            return RedirectToAction(nameof(Index), "Home");
        }

        /// <summary>
        /// 详情页面加载订单详情
        /// </summary>
        /// <param name="uid">对于的订单号</param>
        /// <returns></returns>
        public IActionResult Details(int uid)
        {
            return View();
        }

        public IActionResult AddOrder()
        {
            var claim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Id");
            AddOrderModel addOrder = new AddOrderModel();
            addOrder.contactInfos = _accountService.GetUserContactInfo(Convert.ToInt32(claim?.Value)).ToList();
            addOrder.productInCart = _cartService.GetProductInCart(Convert.ToInt32(claim?.Value)).ToList();
            return View(addOrder);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrder(int contractId)
        {
            var claim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "Id");
           var productInCart = _cartService.GetProductInCart(Convert.ToInt32(claim?.Value)).ToList();
            Dictionary<Product, int> products = new Dictionary<Product, int>();
            foreach(var item in productInCart)
            {
                products.Add(item.Product, item.Quantity);
            }
           await _orderService.SubmitOrder(Convert.ToInt32(claim?.Value), contractId,products);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineStore.Web/Views/Shared/PersonalBusinessDropDownList.cshtml
@{
    ViewData["Title"] = "PersonalBusinessDropDownList";
}

    <ul class="" >
        <li>
            <a asp-controller="Orders" asp-action="Index">我的订单&nbsp;</a>
        </li>
        <li>
            <a  asp-controller="Cart" asp-action="Index" >购物车&nbsp;</a>
        </li>
        <li class="dropdown">
            <a href="#"  data-toggle="dropdown">我的账户&nbsp;</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="User" asp-action="Edit" style="color:blue;">修改个人信息</a>
                <a class="dropdown-item" asp-controller="User" asp-action="AddAddress" style="color:blue;">收货信息管理</a>
                <a asp-controller="User" asp-action="Logout" class="dropdown-item" style="color:blue;">退出登录</a>
                
            </div>
        </li>

    </ul>

OnlineStore.Web/Views/Shared/SearchProductInfo.cshtml
@{
    ViewData["Title"] = "SearchProductInfo";
}

<form asp-action="SearchProduct" method="post" class="searchBox input-group">
    <input id="input_txt" name="inputContext" type="text" class="form-control" placeholder="请输入书名" asp-route-chooseType="书名">
    <div class="input-group-prepend">
        <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
            查询类型
        </button>
        <div class="dropdown-menu">
            <a id="a_name" class="dropdown-item" onclick="Choose">书名</a>
            <a id="a_type" class="dropdown-item" onclick="Choose">类型</a>
            <a id="a_author" class="dropdown-item" onclick="Choose">作者</a>
            <a id="a_publisher" class="dropdown-item" onclick="Choose">出版社</a>
            <a id="a_isbn" class="dropdown-item" onclick="Choose">ISBN</a>
        </div>
    </div>
    <button id="btn" class="btn btn-info btn-search">查找</button>
</form>

<script src="~/js/chooseInputType.js"></script>

OnlineStore.Web/Views/Shared/TopBar.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "TopBar";
}

<span>欢迎来到天玺书城&nbsp;</span>
@if (User.Identity.IsAuthenticated)
{
    <span>@User.Claims.FirstOrDefault(u => u.Type == ClaimTypes.Name).Value</span>
    <span>你好！</span>
}
else
{
    <a asp-action="Login" asp-controller="User">登录</a>
    <a asp-action="Register" asp-controller="User">注册</a>
}

OnlineStore.Web/Views/Shared/_AddAddress.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/AddAdTable.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <base target="_self" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/js/city.js"></script>
    <script src="~/js/getAddressmethod.js"></script>
    <script type="text/javascript" src="~/js/AddAddressJS.js"></script>
    <script src="~/js/AddAd1.js"></script>
</body>

</html>

OnlineStore.Web/Views/Shared/_CommentLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

OnlineStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - OnlineStore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Default" asp-action="Index">OnlineStore.Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Default" asp-action="Index">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AddAddress">AddAddress</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - OnlineStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)
</body>
</html>

OnlineStore.Web/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - OnlineStore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/css/UAddComment.css" rel="stylesheet" />
    <link href="~/css/AddToCart.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="~/css/baseModel1.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="topbar container-fluid">
        <div class="container">
            <div class="row">
                <!-- 左侧登录注册栏 -->
                <div class="loginArea col-md-3">
                    <partial name="Topbar" />
                </div>


                <!-- 右侧个人业务栏 -->
                <div class="webTool col-md-4 offset-md-5">
                    <partial name="PersonalBusinessDropDownList" />
                </div>
            </div>
        </div>
    </div>

    <div class="searchBar container">
        <div class="row">
            <div class="logo col-md-4">
                <a href="/" title="天玺商城"><img src="~/images/logo.png"></a>
            </div>
            <div class="searchBox input-group col-md-5">
                @*<input type="text" class="form-control" placeholder="请输入书名">
        <span class="input-group-btn">
            <button class="btn btn-info btn-search">查找</button>
        </span>*@

                @*<form asp-action="" method="post" class="searchBox input-group">
                    <input id="input_txt" type="text" class="form-control" placeholder="请输入书名">
                    <div class="input-group-prepend">
                        <button id="btn" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown">
                            查询类型
                        </button>
                        <div class="dropdown-menu">
                            <span id="a_name" class="dropdown-item" onclick="Choose">书名</span>
                            <span id="a_type" class="dropdown-item">类型</span>
                            <span id="a_author" class="dropdown-item">作者</span>
                            <span id="a_publisher" class="dropdown-item">出版社</span>
                            <span id="a_isbn" class="dropdown-item">ISBN</span>
                        </div>
                    </div>
                </form>*@
                <partial name="SearchProductInfo" />



            </div>
            <div class="col-md-3">

            </div>
        </div>
    </div>
    <div class="container-fluid navigation">
        <nav class=" navbar navbar-inverse container navbar-expand-md" role="navigation">
            <div class="container" style="text-align: center">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="row  navbar-nav">
                        <li class="col-md-2 col-lg-2"><a asp-action="index" asp-controller="Home">首页</a></li>
                        <li class="col-md-2 col-lg-2"><a href="">畅销榜</a></li>
                        <li class="col-md-2 col-lg-2"><a href="">聚划算</a></li>
                        <li class="col-md-2 col-lg-2"><a href="">出版社</a></li>
                        <li class="col-md-4 col-lg-4"><a href="">关于我们</a></li>


                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="container" style="margin-bottom:100px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- 底部信息栏 -->
    <div class="container">
        <div class="row">
            <!-- 部分：一 -->
            <div class="col-md-3">
                <p>新手上路</p>
                <ul>
                    <li> <a asp-controller="" asp-action="">注册用户</a></li>
                    <li><a asp-controller="" asp-action="">更改注册信息</a></li>
                    <li><a asp-controller="" asp-action="">购物常见的问题</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <p>购物问题</p>
                <ul>
                    <li><a asp-controller="" asp-action="">订单跟踪</a></li>
                    <li><a asp-controller="" asp-action="">历史订单</a></li>
                    <li><a asp-controller="" asp-action="">发货地点 范围</a></li>
                </ul>
            </div>
            <!-- 部分：二 -->
            <div class="col-md-3">
                <p>售后服务</p>
                <ul>
                    <li><a asp-controller="" asp-action="">取消订单</a></li>
                    <li><a asp-controller="" asp-action="">退货</a></li>
                    <li><a asp-controller="" asp-action="">投诉与建议</a></li>
                </ul>
            </div>
            <!-- 部分：三 -->
            <div class="col-md-3">
                <p>其他信息</p>
                <ul>
                    <li><a asp-controller="" asp-action="">本站简介</a></li>
                    <li><a asp-controller="" asp-action="">联系我们</a></li>
                    <li><a asp-controller="" asp-action="">招聘英才</a></li>
                </ul>
            </div>
        </div>
    </div>


    <div class="container footer">
        <div>
            <hr />
            Copyright &copy; &nbsp;&nbsp;2008-2013&nbsp;
            <a href="#">四人帮科技有限公司</a> ALL RIGHT RESERVED<br />
            联系方式：YOLC@gmail.com<br />
            ICP:<a href="#">粤ICP备05021949</a>
        </div>
    </div>
    <script src="~/js/UAddComment.js"></script>
    <script src="~/js/chooseInputType.js"></script>
    
</body>
</html>